# Part of Govoo. See LICENSE file for full copyright and licensing details.

from odoo.tests import tagged
from odoo.tests.common import TransactionCase


@tagged('post_install', '-at_install')
class TestResCompanyTracking(TransactionCase):
    """govoo_base.md: all six govoo_* fields on res.company track changes."""

    def setUp(self):
        super().setUp()
        self.company = self.env.company

    def test_all_six_fields_have_tracking(self):
        fields_info = self.company.fields_get([
            'govoo_company_number',
            'govoo_tin',
            'govoo_incorporation_date',
            'govoo_entity_type',
            'govoo_registered_office_id',
            'govoo_financial_year_end',
        ])
        for field_name in fields_info:
            field = self.env['res.company']._fields[field_name]
            self.assertTrue(field.tracking, '%s should have tracking=True' % field_name)

    def test_changing_field_logs_tracking_message(self):
        message_count_before = len(self.company.message_ids)
        self.company.govoo_company_number = 'RDB/2026/000123'
        # Tracking messages are generated by a precommit callback, not
        # immediately on write.
        self.env.flush_all()
        self.env.cr.precommit.run()
        self.assertGreater(
            len(self.company.message_ids), message_count_before,
            'Changing a tracked field should log a chatter message.',
        )
